GRID_NUM_START = 1
PLOT_PREFIX_TCOLL_CORES = "tcoll_cores"
PLOT_PREFIX_SINK_HISTORY = "sink_history"
PLOT_PREFIX_PDF_PSPEC = "PDF_Pspecs"
PLOT_PREFIX_RHOC_EVOLUTION = "central_density_evolution"
PLOT_PREFIX_MASS_RADIUS= "mass_radius"
