"""Build CIE Lambda_q(T) cooling-efficiency tables using ChiantiPy
(GF12 equivalent).

For each ion of each followed element, computes the bound-bound
line cooling efficiency Lambda_q(T) via
`ChiantiPy.core.ion(...).boundBoundLoss()`, tabulated on the same
T grid as the ioneq tables (101 log-spaced points, 1e4 K to 1e9
K).

Convention used in this table
-----------------------------
Our output is **per ion per electron**, low-density limit:

    cooling rate / volume = Lambda_q(T) * n(X^q) * n_e   [erg / cm^3 / s]

Units of Lambda_q: erg cm^3 / s.

No abundance, no x_q baked in. Combine with whatever ionization
fractions + abundance the application provides.

Conversion to other conventions
-------------------------------
Three conventions are common in the cooling literature; explicit
formulas for each:

1. Lambda_e (per H per electron, GF12 and most CIE-table papers):

       cooling rate / volume = n_H * n_e * Lambda_e

       Lambda_e(T) = sum_q x_q(T) * (n_X / n_H) * Lambda_q(T)

   summed over all ions q (and elements X). x_q comes from
   whichever ionization equilibrium the paper assumes (CIE for
   GF12; PI for HII regions).

2. Lambda_NCR (per H^2, Tigris-NCR / TIGRESS convention):

       cooling rate / volume = n_H^2 * Lambda_NCR

       Lambda_NCR(T) = (n_e / n_H) * Lambda_e(T)

   For fully ionized H + He, n_e/n_H ~= 1.1-1.2 in CIE; for PI
   equilibrium in an HII region the ratio depends on the local
   conditions.

3. Lambda_q (per ion per electron, ChiantiPy convention used in
   this table):

       cooling rate / volume from ion q = n(X^q) * n_e * Lambda_q

   No abundance or x_q baked in -- multiplied at use time as
   shown in convention (1) above.

The reference for the format is Gnat & Ferland 2012, ApJS 199, 20,
whose tables are shipped under
`pyathena/data/microphysics/Gnat_Ferland12_tables/<Element>.txt`.
GF12 tabulates Lambda_q per ion per electron in the same
convention used here (no abundance, no x_q baked in). Their final
`<Element>{CIE}` column is the GS07-CIE-weighted sum
`sum_q x_q^CIE * Lambda_q`. Spot-check at T=1e4 K, OIII:
    ChiantiPy (our build):  7.07e-21 erg cm^3/s per ion per e
    GF12 O{2+} reference :  7.13e-21
matches to 0.8%.

A future `cool_chianti.py` (parallel to
`pyathena.microphysics.cool_gnat12.CoolGnat12`) will combine
these per-ion tables with our CIE ioneq tables
(`ioneq_<element>.txt`) and `pyathena.microphysics.abundance_solar
.AbundanceSolar` (Draine 2011 Table 1.4 / Asplund+2009 protosolar)
to produce the total Lambda_e(T) ready for TIGRESS use.

Computed for the photchem followed-element set:
    H, He, C, N, O, Ne, Mg, Si, S, Ar, Ca, Fe.

CLI:
    XUVTOP=$HOME/Dropbox/Projects/CHIANTI_db \\
        python -m pyathena.photchem.data.build_cool_tables
"""

import os
import warnings
import numpy as np

from .build_ioneq_tables import ELEMENTS


_ELEM_SYM = {
    'H':  'h',  'He': 'he', 'C':  'c',  'N':  'n',  'O':  'o',
    'Ne': 'ne', 'Mg': 'mg', 'Si': 'si', 'S':  's',  'Ar': 'ar',
    'Ca': 'ca', 'Fe': 'fe',
}

# Reference electron density for the low-density (n << n_crit)
# limit. Per-ion bound-bound cooling efficiency scales linearly in
# n_e at low n_e and reaches a saturated plateau as n_e approaches
# n_crit. For per-ion-per-electron tabulation we want the low-n
# limit, so use a very small reference n_e.
_NE_REF = 1.0   # cm^-3


def write_ascii(path, element, Z, log_T, Lambda_q):
    """Write per-element ASCII cooling table.

    Format mirrors `ioneq_<element>.txt`:
      log_T_K column + Lambda_<element>{q}/(n_ion * n_e) columns for
      q = 0 .. Z, all on the same T grid.
    """
    NT = len(log_T)
    with open(path, 'w') as f:
        f.write(f"# CIE bound-bound cooling efficiency for {element} "
                f"(Z={Z})\n")
        f.write(f"# Source: CHIANTI v11.0.2 via ChiantiPy "
                f"ion.boundBoundLoss\n")
        f.write(f"# Units: erg cm^3 / s, per ion per electron, "
                f"low-density limit (n_e = {_NE_REF:g} cm^-3)\n")
        f.write(f"# T grid: {NT} log-spaced points, "
                f"10^{log_T[0]:.2f} K -> 10^{log_T[-1]:.2f} K\n")
        f.write(f"# Generated by "
                f"pyathena/photchem/data/build_cool_tables.py\n")
        f.write(f"#\n")
        cols = ['log_T_K']
        for q in range(Z + 1):
            cols.append(f'L_{element}{q}')
        f.write("# " + "  ".join(f"{c:<13s}" for c in cols) + "\n")
        for it in range(NT):
            row = [f"{log_T[it]:13.4f}"]
            for q in range(Z + 1):
                row.append(f"{Lambda_q[q, it]:13.6e}")
            f.write("  " + "  ".join(row) + "\n")


def read_cool(path):
    """Read a cool_<element>.txt file."""
    log_T = []
    rows = []
    Z = None
    element = None
    with open(path) as f:
        for ln in f:
            s = ln.strip()
            if s.startswith("#"):
                if 'cooling efficiency for' in s and 'Z=' in s:
                    parts = s.split('cooling efficiency for')[-1] \
                        .split('(Z=')
                    element = parts[0].strip()
                    Z = int(parts[1].rstrip(')').strip())
                continue
            if not s:
                continue
            parts = s.split()
            log_T.append(float(parts[0]))
            rows.append([float(p) for p in parts[1:]])
    log_T = np.asarray(log_T)
    Lambda_q = np.asarray(rows).T   # shape (Z+1, NT)
    return dict(log_T=log_T, Z=Z, element=element, Lambda_q=Lambda_q)


def cooling_for_element(element, Z, T_grid):
    """Compute Lambda_q(T) per ion per electron for all q=0..Z of
    one element via ChiantiPy. Returns (Z+1, NT) ndarray.

    ChiantiPy's `boundBoundLoss` automatically multiplies by its
    default elemental abundance (Asplund09 by default) and its
    default CIE ionization fraction at each T -- so the raw return
    is per-H per-electron, NOT per-ion per-electron. To get a
    pure per-ion per-electron cooling efficiency that can be
    combined with arbitrary x_q + abundance at use time, override
    both with 1.0 before calling boundBoundLoss.
    """
    import ChiantiPy.core as ch
    NT = len(T_grid)
    Lambda_q = np.zeros((Z + 1, NT))
    sym = _ELEM_SYM[element]
    for q in range(Z):     # q=Z fully stripped, no bound-bound
        ion_name = f'{sym}_{q + 1}'   # CHIANTI 1-based
        try:
            ion = ch.ion(ion_name, temperature=T_grid,
                         eDensity=_NE_REF)
            # Override defaults so boundBoundLoss returns the per-
            # ion-per-electron cooling efficiency, not GF12-style
            # per-H-per-electron-with-x_q-baked-in.
            ion.Abundance = 1.0
            ion.IoneqOne = np.ones(NT)
            ion.boundBoundLoss()
            rate = np.asarray(ion.BoundBoundLoss['rate'])
        except Exception:
            continue
        if rate.shape != (NT,):
            continue
        # Rate is now per ion per electron at the reference n_e.
        # boundBoundLoss already normalizes by n_e internally
        # (energy flux is independent of n_e in the low-n limit;
        # at higher n_e it saturates as n_crit is approached, but
        # at n_e = 1 cm^-3 we are firmly in the linear regime).
        Lambda_q[q] = np.where(
            np.isfinite(rate) & (rate > 0), rate, 0.0)
    return Lambda_q


def main():
    if not os.environ.get('XUVTOP'):
        raise RuntimeError(
            "XUVTOP environment variable not set. ChiantiPy cannot "
            "load CHIANTI data without it; build_cool_tables would "
            "silently produce all-zero cooling tables. Set XUVTOP "
            "to your CHIANTI v11 data directory before running.")
    warnings.filterwarnings('ignore')
    out_dir = os.path.dirname(os.path.abspath(__file__))
    log_T = np.linspace(4.0, 9.0, 101)
    T_grid = 10.0 ** log_T
    print(f"Building CIE bound-bound cooling tables: "
          f"{len(T_grid)} T points ({T_grid[0]:.2g} -> "
          f"{T_grid[-1]:.2g} K)")
    for element, Z in ELEMENTS.items():
        Lambda_q = cooling_for_element(element, Z, T_grid)
        out_path = os.path.join(out_dir, f"cool_{element}.txt")
        write_ascii(out_path, element, Z, log_T, Lambda_q)
        nonzero_q = int(np.sum(Lambda_q.max(axis=1) > 0))
        max_q = float(Lambda_q.max())
        print(f"  {element:2s} (Z={Z:2d}): wrote {out_path}  "
              f"({nonzero_q}/{Z+1} ions with non-zero L, "
              f"max={max_q:.2e})")


if __name__ == '__main__':
    main()
