"""Build CIE ionization-fraction tables from CHIANTI v11.0.2.

Reads CHIANTI v11's `chianti.ioneq` (Dere et al. 2009 collisional
ionization equilibrium x_q(T) for all elements through Zn) via
ChiantiPy and writes per-element ASCII tables under this directory:

    ioneq_<element>.txt

Format per file: T column (log10(T/K)) followed by one column per
charge state q = 0 to Z. Row q+2 sums to 1 (charge conservation).

CLI:
    XUVTOP=$HOME/Dropbox/Projects/CHIANTI_db \\
        python -m pyathena.photchem.data.build_ioneq_tables
"""

import os
import numpy as np


# Followed elements for the photchem subpackage: same set as the
# atomic-data tables, indexed by atomic number Z. Used as input
# columns for the ASCII tables.
ELEMENTS = {
    'H':  1,
    'He': 2,
    'C':  6,
    'N':  7,
    'O':  8,
    'Ne': 10,
    'Mg': 12,
    'Si': 14,
    'S':  16,
    'Ar': 18,
    'Fe': 26,
}


def write_ascii(path, element, Z, log_T, x_q_array):
    """Write one element's ioneq to ASCII.

    Parameters
    ----------
    element : str        -- 'O', 'Fe', etc.
    Z       : int        -- atomic number
    log_T   : (NT,) ndarray of log10(T/K)
    x_q_array : (Z+1, NT) ndarray of x_q for q=0..Z
    """
    NT = len(log_T)
    with open(path, 'w') as f:
        f.write(f"# CIE ionization fractions for {element} (Z={Z})\n")
        f.write(f"# Source: CHIANTI v11.0.2 chianti.ioneq "
                f"(Dere et al. 2009)\n")
        f.write(f"# T grid: {NT} log-spaced points, "
                f"10^{log_T[0]:.2f} K -> 10^{log_T[-1]:.2f} K\n")
        f.write(f"# Generated by "
                f"pyathena/photchem/data/build_ioneq_tables.py\n")
        f.write(f"#\n")
        # Header row: log_T_K  x_<element>{q}/total
        cols = [f'log_T_K']
        for q in range(Z + 1):
            cols.append(f'x_{element}{q}')
        f.write("# " + "  ".join(f"{c:<13s}" for c in cols) + "\n")
        for it in range(NT):
            row = [f"{log_T[it]:13.4f}"]
            for q in range(Z + 1):
                row.append(f"{x_q_array[q, it]:13.6e}")
            f.write("  " + "  ".join(row) + "\n")


def read_ioneq(path):
    """Read an ASCII ioneq table back into a dict with keys
    'log_T', 'Z', 'element', 'x_q' (shape (Z+1, NT))."""
    log_T = []
    rows = []
    Z = None
    element = None
    with open(path) as f:
        for ln in f:
            s = ln.strip()
            if s.startswith("#"):
                # Pull element + Z from header line "ionization
                # fractions for O (Z=8)"
                if 'fractions for' in s and 'Z=' in s:
                    parts = s.split('fractions for')[-1].split('(Z=')
                    element = parts[0].strip()
                    Z = int(parts[1].rstrip(')').strip())
                continue
            if not s:
                continue
            parts = s.split()
            log_T.append(float(parts[0]))
            rows.append([float(p) for p in parts[1:]])
    log_T = np.asarray(log_T)
    x_q = np.asarray(rows).T   # shape (Z+1, NT)
    return dict(log_T=log_T, Z=Z, element=element, x_q=x_q)


def main():
    import ChiantiPy.tools.io as cio
    out_dir = os.path.dirname(os.path.abspath(__file__))
    ioneq = cio.ioneqRead('chianti')
    T = np.asarray(ioneq['ioneqTemperature'])   # K (linear)
    log_T = np.log10(T)
    ioneqAll = np.asarray(ioneq['ioneqAll'])    # (Zmax, qmax+1, NT)
    print(f"Loaded CHIANTI ioneq: {len(T)} T points "
          f"({T[0]:.2g} -> {T[-1]:.2g} K)")
    for element, Z in ELEMENTS.items():
        # ChiantiPy convention: ioneqAll[Z-1, q, T_idx] is x_q of
        # element Z, charge q = 0..Z (q=0 = neutral).
        x_q = ioneqAll[Z - 1, :Z + 1, :]
        out_path = os.path.join(out_dir, f"ioneq_{element}.txt")
        write_ascii(out_path, element, Z, log_T, x_q)
        # Sanity: each column should sum to ~1 (charge conservation).
        col_sum = x_q.sum(axis=0)
        print(f"  {element:2s} (Z={Z:2d}): wrote {out_path}  "
              f"(col sums {col_sum.min():.4f} - {col_sum.max():.4f})")


if __name__ == '__main__':
    main()
