"""Build CIE ionization-fraction tables from CHIANTI v11.0.2.

Reads CHIANTI v11's `chianti.ioneq` (Dere et al. 2009 collisional
ionization equilibrium x_q(T) for all elements through Zn) via
ChiantiPy and writes per-element ASCII tables under this directory:

    ioneq_<element>.txt

Format per file: T column (log10(T/K)) followed by one column per
charge state q = 0 to Z. Row q+2 sums to 1 (charge conservation).

CLI:
    XUVTOP=$HOME/Dropbox/Projects/CHIANTI_db \\
        python -m pyathena.photchem.data.build_ioneq_tables
"""

import os
import numpy as np


# Followed elements for the photchem subpackage, indexed by atomic
# number Z. Matches the set tabulated by Gnat & Sternberg 2007 for
# direct benchmark comparison.
ELEMENTS = {
    'H':  1,
    'He': 2,
    'C':  6,
    'N':  7,
    'O':  8,
    'Ne': 10,
    'Mg': 12,
    'Si': 14,
    'S':  16,
    'Ar': 18,
    'Ca': 20,
    'Fe': 26,
}


def write_ascii(path, element, Z, log_T, x_q_array):
    """Write one element's ioneq to ASCII.

    Parameters
    ----------
    element : str        -- 'O', 'Fe', etc.
    Z       : int        -- atomic number
    log_T   : (NT,) ndarray of log10(T/K)
    x_q_array : (Z+1, NT) ndarray of x_q for q=0..Z
    """
    NT = len(log_T)
    with open(path, 'w') as f:
        f.write(f"# CIE ionization fractions for {element} (Z={Z})\n")
        f.write(f"# Source: CHIANTI v11.0.2 chianti.ioneq "
                f"(Dere et al. 2009)\n")
        f.write(f"# T grid: {NT} log-spaced points, "
                f"10^{log_T[0]:.2f} K -> 10^{log_T[-1]:.2f} K\n")
        f.write(f"# Generated by "
                f"pyathena/photchem/data/build_ioneq_tables.py\n")
        f.write(f"#\n")
        # Header row: log_T_K  x_<element>{q}/total
        cols = [f'log_T_K']
        for q in range(Z + 1):
            cols.append(f'x_{element}{q}')
        f.write("# " + "  ".join(f"{c:<13s}" for c in cols) + "\n")
        for it in range(NT):
            row = [f"{log_T[it]:13.4f}"]
            for q in range(Z + 1):
                row.append(f"{x_q_array[q, it]:13.6e}")
            f.write("  " + "  ".join(row) + "\n")


def read_ioneq(path):
    """Read an ASCII ioneq table back into a dict with keys
    'log_T', 'Z', 'element', 'x_q' (shape (Z+1, NT))."""
    log_T = []
    rows = []
    Z = None
    element = None
    with open(path) as f:
        for ln in f:
            s = ln.strip()
            if s.startswith("#"):
                # Pull element + Z from header line "ionization
                # fractions for O (Z=8)"
                if 'fractions for' in s and 'Z=' in s:
                    parts = s.split('fractions for')[-1].split('(Z=')
                    element = parts[0].strip()
                    Z = int(parts[1].rstrip(')').strip())
                continue
            if not s:
                continue
            parts = s.split()
            log_T.append(float(parts[0]))
            rows.append([float(p) for p in parts[1:]])
    log_T = np.asarray(log_T)
    x_q = np.asarray(rows).T   # shape (Z+1, NT)
    return dict(log_T=log_T, Z=Z, element=element, x_q=x_q)


def main():
    """Build per-element x_q(T) using ChiantiPy's dynamic ioneq
    solver (`ChiantiPy.core.ioneq.calculate`), which evaluates the
    sequential CIE balance with CURRENT CHIANTI v11 rate fits at
    each T (Badnell DR + Verner-Ferland RR + Dere 2007 CI). This is
    superior to reading the static `chianti.ioneq` file shipped
    with CHIANTI, which is Dere et al. 2009 frozen and does NOT
    reflect ~15 years of subsequent atomic-data updates.

    Use the same T grid as the legacy chianti.ioneq (101 log-spaced
    points, 1e4 to 1e9 K) so existing plots and downstream tools
    remain compatible.
    """
    import ChiantiPy.core as ch
    out_dir = os.path.dirname(os.path.abspath(__file__))
    # T grid matches the chianti.ioneq native grid for compat.
    log_T = np.linspace(4.0, 9.0, 101)
    T = 10.0 ** log_T
    print(f"Computing ioneq with ChiantiPy.core.ioneq.calculate "
          f"(current CHIANTI v11 rate fits): "
          f"{len(T)} T points ({T[0]:.2g} -> {T[-1]:.2g} K)")
    for element, Z in ELEMENTS.items():
        ie = ch.ioneq(Z)
        ie.calculate(T)
        x_q = np.asarray(ie.Ioneq)        # (Z+1, NT)
        out_path = os.path.join(out_dir, f"ioneq_{element}.txt")
        write_ascii(out_path, element, Z, log_T, x_q)
        col_sum = x_q.sum(axis=0)
        print(f"  {element:2s} (Z={Z:2d}): wrote {out_path}  "
              f"(col sums {col_sum.min():.4f} - {col_sum.max():.4f})")


if __name__ == '__main__':
    main()
