"""Unit tests for the Phase 4 CIE high-pool builder.

Validates the closed-form sums in `compute_pool` on synthetic inputs
+ checks the readback round-trip on the actual O table the builder
writes to `data/chemistry/cie_high_pool_O.txt` (must already exist
on disk -- generated by running `python -m
pyathena.chemistry.tables.chianti_v11.build_cie_high_pool`).
"""
from __future__ import annotations

import os

import numpy as np
import pytest

from pyathena.chemistry.tables.chianti_v11.build_cie_high_pool import (
    compute_pool, read_cie_high_pool, _resolve_output_dir,
)


def test_compute_pool_sums_correctly():
    """compute_pool reduces an artificial (Z+1, NT) input to the
    expected three columns. Choose values where every sum is easy
    to verify by hand.
    """
    # Element with Z=4, NT=3 T-points; tracked = first 2 charges
    # (q = 0, 1); pool covers q = 2, 3, 4.
    #
    # At T-point 0: ioneq = [0.5, 0.3, 0.15, 0.04, 0.01]  -> pool
    #               sum = 0.20; pool q_mean = (2*0.15 + 3*0.04 +
    #               4*0.01) / 0.20 = (0.30+0.12+0.04)/0.20 = 2.30.
    # At T-point 1: ioneq = [0.0, 0.0, 0.3, 0.5, 0.2]    -> pool
    #               sum = 1.00; q_mean = (2*0.3+3*0.5+4*0.2)/1.0 =
    #               0.6+1.5+0.8 = 2.90.
    # At T-point 2: ioneq = [0.4, 0.4, 0.1, 0.05, 0.05]  -> pool
    #               sum = 0.20; q_mean = (0.20+0.15+0.20)/0.20 = 2.75.
    ioneq = np.array([
        [0.5, 0.0, 0.4],
        [0.3, 0.0, 0.4],
        [0.15, 0.3, 0.1],
        [0.04, 0.5, 0.05],
        [0.01, 0.2, 0.05],
    ])
    # L_q is per-ion, in erg cm^3 / s. Easy values for hand check.
    L_q = np.array([
        [0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0],
        [1.0e-22, 1.0e-22, 1.0e-22],
        [2.0e-22, 2.0e-22, 2.0e-22],
        [3.0e-22, 3.0e-22, 3.0e-22],
    ])

    x_high, q_mean, Lambda_high = compute_pool(ioneq, L_q,
                                                q_max_tracked=2)
    # x_high (sum over q >= 2)
    np.testing.assert_allclose(x_high, [0.20, 1.00, 0.20],
                                rtol=1e-14)
    # q_mean (population-weighted)
    np.testing.assert_allclose(q_mean, [2.30, 2.90, 2.75],
                                rtol=1e-14)
    # Lambda_high = sum_q ioneq_q * L_q for q in pool
    # T0: 0.15*1e-22 + 0.04*2e-22 + 0.01*3e-22 = (0.15+0.08+0.03)e-22 = 0.26e-22
    # T1: 0.3*1 + 0.5*2 + 0.2*3 = 0.3+1.0+0.6 = 1.9 -> 1.9e-22
    # T2: 0.1+0.10+0.15 = 0.35e-22
    np.testing.assert_allclose(
        Lambda_high, [0.26e-22, 1.9e-22, 0.35e-22], rtol=1e-14)


def test_compute_pool_handles_empty_pool():
    """When the pool fraction is exactly zero (no ionised population
    above q_max), q_high_mean is set to zero rather than NaN, and
    Lambda_high is exactly zero.
    """
    ioneq = np.array([
        [1.0, 1.0],
        [0.0, 0.0],
        [0.0, 0.0],
    ])
    L_q = np.array([
        [0.0, 0.0],
        [1.0e-22, 1.0e-22],
        [1.0e-22, 1.0e-22],
    ])
    x_high, q_mean, Lambda_high = compute_pool(ioneq, L_q,
                                                q_max_tracked=1)
    np.testing.assert_array_equal(x_high, [0.0, 0.0])
    np.testing.assert_array_equal(q_mean, [0.0, 0.0])
    np.testing.assert_array_equal(Lambda_high, [0.0, 0.0])


def test_pre_built_O_table_is_well_formed():
    """If the builder has been run, the O table on disk must have a
    monotonic T-grid, x_high_frac in [0, 1], q_high_mean between the
    pool min (3) and the element Z (8) when the pool is non-empty,
    and non-negative Lambda_high. This guards against silent format
    regressions.
    """
    path = os.path.join(_resolve_output_dir(),
                        'cie_high_pool_O.txt')
    if not os.path.isfile(path):
        pytest.skip(
            f'no pre-built table at {path}; run '
            '`python -m pyathena.chemistry.tables.chianti_v11.'
            'build_cie_high_pool` first.'
        )
    tbl = read_cie_high_pool(path)
    assert tbl['element'] == 'O'
    assert tbl['Z'] == 8
    assert tbl['q_max_tracked'] == 3

    log_T = tbl['log_T']
    assert np.all(np.diff(log_T) > 0)

    x = tbl['x_high_frac']
    assert np.all(x >= 0.0)
    assert np.all(x <= 1.0 + 1e-12)

    q = tbl['q_high_mean']
    L = tbl['Lambda_high']
    assert np.all(L >= 0.0)

    # Where the pool is non-trivial, the mean charge sits between the
    # pool floor and the fully-stripped Z.
    nontrivial = x > 1.0e-6
    assert np.all(q[nontrivial] >= tbl['q_max_tracked'] - 1.0e-12)
    assert np.all(q[nontrivial] <= tbl['Z'] + 1.0e-12)

    # And at the hot end of the grid the pool fraction must approach
    # unity (O is fully ionised at log T = 9).
    assert x[-1] > 0.99
